# Supervised Intent Clustering
# This is a package to fine-tune language models in order to create clustering-friendly embeddings.
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.  
# SPDX-License-Identifier: CC-BY-NC-4.0

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5

language_model_learning_rate: 1e-5
language_model_weight_decay: 1e-2
  
# xlm-roberta-base
# sentence-transformers_all-mpnet-base-v2
# paraphrase-multilingual-mpnet-base-v2
# bert-base-multilingual-cased

gpu: [0]

base_model_name: 'paraphrase-multilingual-mpnet-base-v2'

sentence_transformer_model_name: 'base_language_models/${model.base_model_name}'
embeddings_length: 768
dropout: 0.5

#contrastive_learning, cosine_similarity_loss, triplet_margin_loss, supervised_learning, binary_classification
training_objective: 'supervised_learning' 

distance_matrix_for_supervised: 'cosine_distance' #cosine_distance, linear_score
triplet_margin: 0.1
contrastive_margin: 1.6
C: 5
r: 1.0

